## packages

In [1]:
import nltk
from tkinter import *
import pyarabic.arabrepr
import re
#stem  
from tashaphyne.stemming import ArabicLightStemmer
arepr=pyarabic.arabrepr.ArabicRepr()
repr=arepr.repr
arabic_stemmer=ArabicLightStemmer()

## read the data

In [2]:
import pandas as pd
fake=pd.read_csv('E:/nbn/fake-news.csv',encoding='utf-8')
real=pd.read_csv('E:/nbn/real-news.csv',encoding='utf-8')
real['label']=1
fake['label']=0
real=real[:5000]
fake=fake[:5000]
df=pd.concat([real,fake])
#4999-0
df.head()

text  label
0  سحبت شركة غوغل في خطوة مفاجئة خدمة يوتيوب الشه...      1
1  عاد لاعب باريس سان جيرمان  البرازيلي نيمار دا ...      1
2  أخبارنا المغربية ـ متابعة   في أول رد للبرلمان...      1
3  شيرين تتهرب من المؤتمر الصحفي لمهرجان تطوان و ...      1
4  منظمو أولمبياد طوكيو 2020 يطالبون بالتبرع باله...      1

## preprocessing

In [3]:
df.tail()

text  label
4995                       صورة لقلعة هتلر في ألمانيا        0
4996  اجتماع رئيس حركة الهضة راشد الغنوشي مع زعيم ال...      0
4997  فتاة أفغانية كشفت وجهها ليصورها ستيف ماكوري ال...      0
4998  صورة ت ظهر رئيس حكومة الوفاق الليبية فايز السر...      0
4999  صورة ت ظهر أسلحة صيد تمت مصادرتها ثم  إتلافها ...      0

# shuffel the data

In [4]:
from sklearn.utils import shuffle
df=shuffle(df)
df.head()

text  label
413   فاز منتخب بوركينا فاسو على نظيره الغاني في مبا...      1
735   ترشيح لجائزة الانحياز الواضح   مسلمون يتضرعون ...      0
4380  أثارت تصريحات المدير التنفيذي لشركة  شياومي  ا...      1
1464     ترامب يقترح على إسبانيا بناء جدار في الصحرا...      0
4963  صورة لخفاش في حجم الإنسان  ع ثر عليه في الفلبين        0

# reset indexes

In [5]:
df["text"][1]

1    طالب توجيهي يكتشف حبه لمتابعة النشرة الاقتصادي...
1    عاد لاعب باريس سان جيرمان  البرازيلي نيمار دا ...
Name: text, dtype: object

In [6]:
df=df.sample(frac=1).reset_index(drop=True)
#Return a random sample of items from an axis of object.
#frac is A random n% sample of the DataFrame with replacement
df.head()

text  label
0   خلال_ايام   إعلان الغاء الدوري   السعودي   ال...      0
1  الأعمار الحقيقية لأشهر الفنانات العربيات    بي...      1
2  قال بحث جديد إن الشوكولا الداكنة تفيد مثل الشم...      1
3  قالت  أخبار اليوم  في عددها الصادر غدا أن حميد...      1
4  أخبارنا المغربية     أفاد بلاغ لوزراة الداخلية...      1

In [7]:
import string
punc=list(string.punctuation)
file=open('E:/nbn/stopwords.txt','r',encoding='utf-8')
ss=file.read()

stop_words=ss.split()


In [8]:
df["text"][1]

'الأعمار الحقيقية لأشهر الفنانات العربيات    بينما ترفض فنانات الكشف عن أعمارهن الحقيقية  هناك أخريات يتباهين بأعمارهن خلال استضافتهن في البرامج  مؤكدات أن هن لا يخشين التقدم في السن     شيرين عبد الوهاب آخر الفنانات اللواتي كشفن عن عمرهن  فاجأت النجمة المصرية الجميع في برنامج  ذا فويس   بالإعلان عن عمرها الحقيقي  فبعدما أبدت إعجابها بمتسابق مصري  سألته عن عمره فأخبرها أنه في العشرين  عندها  ردت قائلة   يعني أنا أكبر منك بـ14 عاما    أي أنها تبلغ 34 عاما   يومها  غازلها كاظم الساهر  قائلا  بأن ها تبدو أصغر من المتسابق بـ5 سنوات  مما أثار ضحك شيرين التي شكرته على مجاملته الرقيقة    وقبلها  كشفت غادة عبد الرازق عن عمرها الحقيقي خلال حوارها مع المذيعة منى عبد الوهاب ضمن برنامج  مصارحة حرة  على قناة      يومها  أشارت إلى أن ها تبلغ 44 عاما   مواليد 6 يوليو 1970   متحدية  أي شخص أن يثبت عكس هذا الكلام  وبالرغم من إعلان غادة عن عمرها في أكثر من مناسبة  إلا أن  هناك من يراها أكبر بسنوات  وكشفت علا غانم عن عمرها الحقيقي خلال استضافتها في برنامج  بدون مكياج  الذي قدمه طوني خليفة على قناة  القاه

In [9]:

def remove_stopwords1():
    result_data.delete("1.0",END)
    text=rawdata.get("1.0",END)
    results=[]
    for word in text.split():
        if word not in stop_words:

            results.append(word)
    result_data.insert("1.0"," - ".join(results))


In [10]:
def choose_text():
    import random
    n=random.randint(0,len(df))
    rawdata.delete('1.0',END)
    rawdata.insert("1.0",df['text'][n])

In [11]:
def splitting1():
    result_data.delete("1.0",END)
    text=rawdata.get("1.0",END)
    results=[]
    for word in text.split():
        results.append(word)
    result_data.insert("1.0"," - ".join(results))
def stemming1():
    result_data.delete("1.0",END)
    text=rawdata.get("1.0",END)
    results=[]
    for word in text.split():
        word=u"{}".format(word)
        arabic_stemmer.light_stem(word)
        results.append(arabic_stemmer.get_stem())
    result_data.insert("1.0"," - ".join(results))
def get_root1():
    
    result_data.delete("1.0",END)
    text=rawdata.get("1.0",END)
    results=[]
    for word in text.split():
        word=u"{}".format(word)
        arabic_stemmer.light_stem(word)
        results.append(arabic_stemmer.get_root())
    result_data.insert("1.0"," - ".join(results))


In [12]:
def segmentation1():
    result_data.delete("1.0",END)
    text=rawdata.get("1.0",END)
    results=[]
    for word in text.split('.'):
        results.append(word)
    result_data.insert("1.0"," - ".join(results))

In [13]:
import pyaramorph
analyzer=pyaramorph.Analyzer()
def analyze_text():
    result_data.delete("1.0",END)
    text=rawdata.get("1.0",END)
    results=analyzer.analyze_text(text)
    
    result_data.insert("1.0",results)

loading dictPrefixes ... loaded 299 entries
loading dictStems ... loaded 38600 lemmas and 82158 entries
loading dictSuffixes ... loaded 618 entries


In [14]:
top=Tk()
top.title('Fake News')
top.geometry("575x600") 
label1=Label(top,text='Enter your Text')
rawdata=Text(top,height=15,width=60,)
label2=Label(top,text='Result')
result_data=Text(top,height=15,width=60,)
stem_button=Button(top,text="Stem",command=stemming1)
segmentation_button=Button(top,text="Segmentation",command=segmentation1)
get_root_button=Button(top,text="Get Root",command=get_root1)
split_button=Button(top,text="Split Text",command=splitting1)
stopwords_button=Button(top,text="Remove StopWords",command=remove_stopwords1)
analyz_button=Button(top,text="Analyze Text",command=analyze_text)
random_button=Button(top,text="Random text from data",command=choose_text)



label1.grid(row=0,columnspan=7)
rawdata.grid(row=1,columnspan=7)
label2.grid(row=2,columnspan=7)
result_data.grid(row=3,columnspan=7)
split_button.grid(row=4,column=0)
segmentation_button.grid(row=4,column=1)
stopwords_button.grid(row=4,column=2)
stem_button.grid(row=4,column=3)
get_root_button.grid(row=4,column=4)
analyz_button.grid(row=4,column=5)
random_button.grid(row=4,column=6)

top.mainloop()

In [15]:
def segmentation(text):
    results=text.split('.')
    return " ".join(results)

In [16]:
def splitting(text):

    results=text.split()
    #['','']
    return " ".join(results)

In [17]:
def remove_stopwords(text):
    results=[]
    for word in text.split():
        if word not in stop_words:

            results.append(word)
    return " ".join(results)


In [18]:
def remove_punctuation(text):

    t=[]
    for word in text.split(): 
        if word not in punc:
            t.append(word)
            
    return " ".join(t)

In [19]:

def stemming(text):

    results=[]
    for word in text.split():
        word=u"{}".format(word)
        arabic_stemmer.light_stem(word)
        results.append(arabic_stemmer.get_stem())
        
    return " ".join(results)


In [20]:

def get_root(text):
    results=[]
    
    for word in text.split():
        word=u"{}".format(word)
        arabic_stemmer.light_stem(word)
        results.append(arabic_stemmer.get_root())
    return " ".join(results)


In [21]:
def num_pre(q):
    # Replacing some numbers with string equivalents (not perfect, can be done better to account for more cases)
    q = q.replace(',000,000,000 ', 'بليون ')
    q = q.replace(',000,000 ', 'مليون ')
    q = q.replace(',000 ', 'الف ')
    q = re.sub(r'([0-9]+)000000000', r'\بليون ', q)
    q = re.sub(r'([0-9]+)000000', r'\مليون ', q)
    q = re.sub(r'([0-9]+)000', r'\الف ', q)
    azer=u"\u0660"
    anine=u"\u0669"
    q = re.sub(r"[0-9]([0-9a-zA-Zأ-ي{}-{}]|\W|_)+".format(azer,anine), ' ',q)
    q = re.sub(r"_([0-9a-zA-Zأ-ي{}-{}]|\W|\w)+".format(azer,anine), ' ',q)
    return q

# applay the preprocessing

In [22]:
df['text1']=df['text'].apply(remove_stopwords)
df['text1']=df['text1'].apply(num_pre)

In [23]:
df['text1']=df['text1'].apply(remove_punctuation)
df['text1']=df['text1'].apply(get_root)


In [24]:
df['news_len']=df['text1'].str.len()
df['news_num_word']=df['text1'].apply(lambda row: len(row.split()))
df

text  label  \
0      خلال_ايام   إعلان الغاء الدوري   السعودي   ال...      0   
1     الأعمار الحقيقية لأشهر الفنانات العربيات    بي...      1   
2     قال بحث جديد إن الشوكولا الداكنة تفيد مثل الشم...      1   
3     قالت  أخبار اليوم  في عددها الصادر غدا أن حميد...      1   
4     أخبارنا المغربية     أفاد بلاغ لوزراة الداخلية...      1   
...                                                 ...    ...   
9995  لماذا يا اله  لماذا  أنت تسأل و و تساءل أيضا ك...      0   
9996  ابنة المغني مايكل جاكسون   والدي مات مقتولا   ...      1   
9997  سامسونج تطلق أول تلفاز شفاف في العالم في حركة ...      0   
9998     محافظ تركي يلوح بـ ذو الفقار  متوعدا بدخول ...      0   
9999  صورة تظهر إصابة أربعة متطوعين بشلل نصفي في الو...      0   

                                                  text1  news_len  \
0                                                  خلال         4   
1     عمر حقق شهر فنن عرب رفض فنن كشف عمر حقق ءخر به...       194   
2     قول حثث جدد شكل دكن فيد لشمندر بنجر حسس ءدد رض...       803   
3     قلت خبر لوم عدد صدر غدا حمد شبط لقق غلب عقد يو...       417   
4     خبر غرب فود لوغ وزر دخل حزب ءصل عصر و حزب عدل ...        93   
...                                                 ...       ...   
9995  لهه سءل و و سءل كتب صفو صرعب لهه دوع تكك لءم س...      1118   
9996  بنن لمغ مكل جكس ولد موت قتل قلت بنن مكل جكس لح...       405   
9997  مسنج طلق أول لفز شفف علم حرك جرء قوم مسنج مساء...       436   
9998            حفظ ركك لوح بــ فقر وعد دخل وصل قدس صدر        39   
9999        صور ظهر صوب ربع طوع شلل نصف وجه لقق قوح وزر        43   

      news_num_word  
0                 1  
1                48  
2               196  
3               106  
4                25  
...             ...  
9995            286  
9996            101  
9997            105  
9998             10  
9999             11  

[10000 rows x 5 columns]

In [25]:
new_df=df.copy()
new_df=new_df.drop(columns=['text','text1','label'])

# Naive Bayes with Tf_Idf

In [100]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
#feature extraction
tfidf_vec=TfidfVectorizer()
tfidf_features=tfidf_vec.fit_transform(df['text1']).toarray()

temp_df=pd.DataFrame(tfidf_features,index=df.index)

final_df=pd.concat([new_df,temp_df],axis=1)
#split data into train and test
x_train,x_test,y_train,y_test=train_test_split(final_df.iloc[:,:].values,df['label'],test_size=0.25)

In [101]:
print(x_train.shape)
print(x_test.shape)

(7500, 13334)
(2500, 13334)


In [102]:
# classifier
from sklearn.naive_bayes import MultinomialNB
tfidf_model=MultinomialNB()
tfidf_model.fit(x_train,y_train)

MultinomialNB()

# accurcy

In [103]:
import numpy as np
tfidf_predected=tfidf_model.predict(x_test)
print(np.mean(tfidf_predected==y_test))

0.8508


# confusion matrix

In [104]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,tfidf_predected))

[[ 904  320]
 [  53 1223]]


# Random Forest with Tf_Idf

In [105]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred = rf.predict(x_test)
accuracy_score(y_test,y_pred)

0.94

# Naive Bayes with Binary Encoding

In [74]:
from sklearn.feature_extraction.text import CountVectorizer
binary_vec=CountVectorizer(binary=True)
binary_features=binary_vec.fit_transform(df['text1']).toarray() #Learn the vocabulary dictionary and return document-term matrix
#{'':51}

temp_df=pd.DataFrame(binary_features,index=df.index)

final_df=pd.concat([new_df,temp_df],axis=1)
#split data into train and test
x_train,x_test,y_train,y_test=train_test_split(final_df.iloc[:,:].values,df['label'],test_size=0.2)

In [75]:
# classefier
binary_model=MultinomialNB()
binary_model.fit(x_train,y_train)

MultinomialNB()

# accurcy

In [76]:
binary_predicted=binary_model.predict(x_test)
# 1
print(np.mean(binary_predicted==y_test))

0.9115


# Confusion Matrix

In [77]:
print(confusion_matrix(binary_predicted,y_test))

[[861  44]
 [133 962]]


# Random Forest with Binary Encoding

In [78]:
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred = rf.predict(x_test)
accuracy_score(y_test,y_pred)

0.9325

# Naive Bayes with Counting

In [79]:
count_vec=CountVectorizer()
count_features=count_vec.fit_transform(df['text1']).toarray()
temp_df=pd.DataFrame(count_features,index=df.index)

final_df=pd.concat([new_df,temp_df],axis=1)
#split data into train and test
x_train,x_test,y_train,y_test=train_test_split(final_df.iloc[:,:].values,df['label'],test_size=0.2)
count_model=MultinomialNB()
count_model.fit(x_train,y_train)


MultinomialNB()

# accurcy

In [80]:
count_predicted=count_model.predict(x_test)
print(np.mean(count_predicted==y_test))

0.9075


# Confusion Matrix

In [81]:
print(confusion_matrix(count_predicted,y_test))

[[853  35]
 [150 962]]


# Random Forest with Counting

In [82]:
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred = rf.predict(x_test)
accuracy_score(y_test,y_pred)

0.9365