## packages

In [75]:
import nltk
from tkinter import *
import pyarabic.arabrepr
#stem  
from tashaphyne.stemming import ArabicLightStemmer
arepr=pyarabic.arabrepr.ArabicRepr()
repr=arepr.repr
arabic_stemmer=ArabicLightStemmer()

## read the data

In [76]:
import pandas as pd
fake=pd.read_csv('E:/nbn/fake-news.csv',encoding='utf-8')
real=pd.read_csv('E:/nbn/real-news.csv',encoding='utf-8')
real['label']=1
fake['label']=0
real=real[:5000]
fake=fake[:5000]
df=pd.concat([real,fake])
#4999-0
df.head()

text  label
0  سحبت شركة غوغل في خطوة مفاجئة خدمة يوتيوب الشه...      1
1  عاد لاعب باريس سان جيرمان  البرازيلي نيمار دا ...      1
2  أخبارنا المغربية ـ متابعة   في أول رد للبرلمان...      1
3  شيرين تتهرب من المؤتمر الصحفي لمهرجان تطوان و ...      1
4  منظمو أولمبياد طوكيو 2020 يطالبون بالتبرع باله...      1

## preprocessing

In [77]:
df.tail()

text  label
4995                       صورة لقلعة هتلر في ألمانيا        0
4996  اجتماع رئيس حركة الهضة راشد الغنوشي مع زعيم ال...      0
4997  فتاة أفغانية كشفت وجهها ليصورها ستيف ماكوري ال...      0
4998  صورة ت ظهر رئيس حكومة الوفاق الليبية فايز السر...      0
4999  صورة ت ظهر أسلحة صيد تمت مصادرتها ثم  إتلافها ...      0

# shuffel the data

In [78]:
from sklearn.utils import shuffle
df=shuffle(df)
df.head()

text  label
1104  كيف وقف القادة العرب في وجه ترامب ومنعوه من نق...      0
1475  مسؤول يؤكد أن   الشهداء ليسوا فقط مجرد أرقام و...      0
2382  أخبارنا المغربية  وجهت الوزارة صفعة قوية إلى ع...      1
3319  متابعة          أثار عدم تضمين عدد اليوم الاثن...      1
3631  صحيفة ألمانية تقول من بين الشخصيات القوية في ا...      0

# reset indexes

In [79]:
df["text"][1]

1    عاد لاعب باريس سان جيرمان  البرازيلي نيمار دا ...
1    طالب توجيهي يكتشف حبه لمتابعة النشرة الاقتصادي...
Name: text, dtype: object

In [80]:
df=df.sample(frac=1).reset_index(drop=True)
#Return a random sample of items from an axis of object.
#frac is A random n% sample of the DataFrame with replacement
df.head()

text  label
0  مشاهدة الأفلام السينمائية بتقنية البعد الثالث ...      1
1  أخبارنا المغربية   جمال مايس     نشر الشيخ الس...      1
2  هلي ل يجبر على الاستقالة بعد أن نسي الدعاء لحك...      0
3  أخبارنا المغربية ــ مراكش من المنطز أن تضع ولا...      1
4  كيف تقنع الناس أنك إنسان متدي ن هل تعبت من وصف...      0

In [111]:
import string
punc=list(string.punctuation)
file=open('E:/nbn/stopwords.txt','r',encoding='utf-8')
ss=file.read()

stop_words=ss.split()


AttributeError: 'ArabicLightStemmer' object has no attribute 'stop_words'

In [82]:
df["text"][1]

'أخبارنا المغربية   جمال مايس     نشر الشيخ السلفي حماد القباج تدوينة مثيرة للجدل حيث أثنى فيها على الرئيس المعين الجديد سعد الدين العثماني   ووصفه بأنه ذو مستوى علمي ورصيد نضالي   بل ذهب بعيدا عندما قال أن العثماني فيه مميزات لم تجتمع في 30 حكومة عرفها المغرب بعد الاستقلال من جهتهم اعتبر فيسبوكيين تدوينة الشيخ القباج مليئة شيئا ما بما اسموه النفاق السياسي   فبعدما كان الشيخ يتغزل ببن كيران ويعتبره الزعيم الخارق   وأنه ليس مثله أحد   ويدافع عنه بشراسة   عاد ليقول نفس الكلام في حق العثماني بل اعتبر أن الأخير لم تجتمع ميزاته في 30 حكومة عرفها المغرب بعد الاستقلال   نفاق ياشيخ  هكذا علق فيسبوكي ساخرا  وفيما يلي نص تدوينة القباج  الأخ العزيز والصديق الكبير الدكتور سعد الدين العثماني شخصية وطنية اجتمع فيها ما تفرق في غيرها من الشخصيات السياسية مستوى علمي وثقافي عاليفكر متزن ومستنيررصيد نضالي إصلاحي مشرفتجربة سياسية محترمة   وأستطيع أن أجزم بأن الشخصيات التي ترأست حوالي 30 حكومة عرفها المغرب بعد الاستقلال  لا يوجد فيها من اجتمعت فيه تلك المزايا   وهو ما جعلني أعتقد أن تعيينه رئيسا للحكومة من

In [83]:

def remove_stopwords1():
    result_data.delete("1.0",END)
    text=rawdata.get("1.0",END)
    results=[]
    for word in text.split():
        if word not in stop_words:

            results.append(word)
    result_data.insert("1.0"," - ".join(results))


In [84]:
def choose_text():
    import random
    n=random.randint(0,len(df))
    rawdata.delete('1.0',END)
    rawdata.insert("1.0",df['text'][n])

In [85]:
def splitting1():
    result_data.delete("1.0",END)
    text=rawdata.get("1.0",END)
    results=[]
    for word in text.split():
        results.append(word)
    result_data.insert("1.0"," - ".join(results))
def stemming1():
    result_data.delete("1.0",END)
    text=rawdata.get("1.0",END)
    results=[]
    for word in text.split():
        word=u"{}".format(word)
        arabic_stemmer.light_stem(word)
        results.append(arabic_stemmer.get_stem())
    result_data.insert("1.0"," - ".join(results))
def get_root1():
    
    result_data.delete("1.0",END)
    text=rawdata.get("1.0",END)
    results=[]
    for word in text.split():
        word=u"{}".format(word)
        arabic_stemmer.light_stem(word)
        results.append(arabic_stemmer.get_root())
    result_data.insert("1.0"," - ".join(results))


In [86]:
def segmentation1():
    result_data.delete("1.0",END)
    text=rawdata.get("1.0",END)
    results=[]
    for word in text.split('.'):
        results.append(word)
    result_data.insert("1.0"," - ".join(results))

In [87]:
import pyaramorph
analyzer=pyaramorph.Analyzer()
def analyze_text():
    result_data.delete("1.0",END)
    text=rawdata.get("1.0",END)
    results=analyzer.analyze_text(text)
    
    result_data.insert("1.0",results)

loading dictPrefixes ... loaded 299 entries
loading dictStems ... loaded 38600 lemmas and 82158 entries
loading dictSuffixes ... loaded 618 entries


In [88]:
top=Tk()
top.title('Fake News')
top.geometry("575x600") 
label1=Label(top,text='Enter your Text')
rawdata=Text(top,height=15,width=60,)
label2=Label(top,text='Result')
result_data=Text(top,height=15,width=60,)
stem_button=Button(top,text="Stem",command=stemming1)
segmentation_button=Button(top,text="Segmentation",command=segmentation1)
get_root_button=Button(top,text="Get Root",command=get_root1)
split_button=Button(top,text="Split Text",command=splitting1)
stopwords_button=Button(top,text="Remove StopWords",command=remove_stopwords1)
analyz_button=Button(top,text="Analyze Text",command=analyze_text)
random_button=Button(top,text="Random text from data",command=choose_text)



label1.grid(row=0,columnspan=7)
rawdata.grid(row=1,columnspan=7)
label2.grid(row=2,columnspan=7)
result_data.grid(row=3,columnspan=7)
split_button.grid(row=4,column=0)
segmentation_button.grid(row=4,column=1)
stopwords_button.grid(row=4,column=2)
stem_button.grid(row=4,column=3)
get_root_button.grid(row=4,column=4)
analyz_button.grid(row=4,column=5)
random_button.grid(row=4,column=6)

top.mainloop()

In [89]:
def segmentation(text):
    results=text.split('.')
    return " ".join(results)

In [90]:
def splitting(text):

    results=text.split()
    #['','']
    return " ".join(results)

In [91]:
def remove_stopwords(text):
    results=[]
    for word in text.split():
        if word not in stop_words:

            results.append(word)
    return " ".join(results)


In [92]:
def remove_punctuation(text):

    t=[]
    for word in text.split(): 
        if word not in punc:
            t.append(word)
            
    return " ".join(t)

In [93]:

def stemming(text):

    results=[]
    for word in text.split():
        word=u"{}".format(word)
        arabic_stemmer.light_stem(word)
        results.append(arabic_stemmer.get_stem())
        
    return " ".join(results)


In [94]:

def get_root(text):
    results=[]
    
    for word in text.split():
        word=u"{}".format(word)
        arabic_stemmer.light_stem(word)
        results.append(arabic_stemmer.get_root())
    return " ".join(results)


# applay the preprocessing

In [95]:
#df['text1']=df['text'].apply(remove_stopwords)
df['text1']=df['text'].apply(remove_punctuation)
df['text1']=df['text'].apply(get_root)


# Naive Bayes with Tf_Idf

In [96]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
#feature extraction
tfidf_vec=TfidfVectorizer()
tfidf_features=tfidf_vec.fit_transform(df['text1'])
#split data into train and test
x_train,x_test,y_train,y_test=train_test_split(tfidf_features,df['label'],test_size=0.2)

In [97]:
print(x_train.shape)
print(x_test.shape)

(8000, 16702)
(2000, 16702)


In [98]:
# classifier
from sklearn.naive_bayes import MultinomialNB
tfidf_model=MultinomialNB()
tfidf_model.fit(x_train,y_train)

MultinomialNB()

# accurcy

In [99]:
import numpy as np
tfidf_predected=tfidf_model.predict(x_test)
print(np.mean(tfidf_predected==y_test))

0.928


# confusion matrix

In [100]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,tfidf_predected))

[[879 124]
 [ 20 977]]


# Random Forest with Tf_Idf

In [101]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred = rf.predict(x_test)
accuracy_score(y_test,y_pred)

0.9555

# Naive Bayes with Binary Encoding

In [102]:
from sklearn.feature_extraction.text import CountVectorizer
binary_vec=CountVectorizer(binary=True)
binary_features=binary_vec.fit_transform(df['text1']) #Learn the vocabulary dictionary and return document-term matrix
#{'':51}

x_train,x_test,y_train,y_test=train_test_split(binary_features,df['label'],test_size=0.2)
pd.DataFrame(binary_features.toarray(),columns=sorted(binary_vec.vocabulary_.keys()))

000  00000كء  00212522438138  00218213617808  00218213617809  \
0       0        0               0               0               0   
1       0        0               0               0               0   
2       0        0               0               0               0   
3       0        0               0               0               0   
4       0        0               0               0               0   
...   ...      ...             ...             ...             ...   
9995    0        0               0               0               0   
9996    0        0               0               0               0   
9997    0        0               0               0               0   
9998    0        0               0               0               0   
9999    0        0               0               0               0   

      0021821365101بلنسب  00218612241112  0031  00ر11  00ر15  ...  ﻷكذب  ﻷكل  \
0                      0               0     0      0      0  ...     0    0   
1                      0               0     0      0      0  ...     0    0   
2                      0               0     0      0      0  ...     0    0   
3                      0               0     0      0      0  ...     0    0   
4                      0               0     0      0      0  ...     0    0   
...                  ...             ...   ...    ...    ...  ...   ...  ...   
9995                   0               0     0      0      0  ...     0    0   
9996                   0               0     0      0      0  ...     0    0   
9997                   0               0     0      0      0  ...     0    0   
9998                   0               0     0      0      0  ...     0    0   
9999                   0               0     0      0      0  ...     0    0   

      ﻷمر  ﻷنن  ﻹءنترنت  ﻹنس  ﻹﺩﺍﺭﺓ  ﻻرشف  ﻻﺴـﺘﻤﺭﺍﺭﻴﺔ  ﻻﻨﺘﺨﺎﺒﺎﺕ  
0       0    0        0    0      0     0           0         0  
1       0    0        0    0      0     0           0         0  
2       0    0        0    0      0     0           0         0  
3       0    0        0    0      0     0           0         0  
4       0    0        0    0      0     0           0         0  
...   ...  ...      ...  ...    ...   ...         ...       ...  
9995    0    0        0    0      0     0           0         0  
9996    0    0        0    0      0     0           0         0  
9997    0    0        0    0      0     0           0         0  
9998    0    0        0    0      0     0           0         0  
9999    0    0        0    0      0     0           0         0  

[10000 rows x 16702 columns]

In [103]:
# classefier
binary_model=MultinomialNB()
binary_model.fit(x_train,y_train)

MultinomialNB()

# accurcy

In [104]:
binary_predicted=binary_model.predict(x_test)
# 1
print(np.mean(binary_predicted==y_test))

0.9005


# Confusion Matrix

In [105]:
print(confusion_matrix(binary_predicted,y_test))

[[866  48]
 [151 935]]


# Random Forest with Binary Encoding

In [106]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred = rf.predict(x_test)
accuracy_score(y_test,y_pred)

0.941

# Naive Bayes with Counting

In [107]:
count_vec=CountVectorizer()
count_features=count_vec.fit_transform(df['text1'])
#[[5,5,15]]
x_train,x_test,y_train,y_test=train_test_split(count_features,df['label'],test_size=0.2)
count_model=MultinomialNB()
count_model.fit(x_train,y_train)


MultinomialNB()

# accurcy

In [108]:
count_predicted=count_model.predict(x_test)
print(np.mean(count_predicted==y_test))

0.9015


# Confusion Matrix

In [109]:
print(confusion_matrix(count_predicted,y_test))

[[822  39]
 [158 981]]


# Random Forest with Counting

In [110]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred = rf.predict(x_test)
accuracy_score(y_test,y_pred)

0.943