## packages

In [235]:
import nltk
from tkinter import *
import pyarabic.arabrepr
from tashaphyne.stemming import ArabicLightStemmer
arepr=pyarabic.arabrepr.ArabicRepr()
repr=arepr.repr
arabic_stemmer=ArabicLightStemmer()


## read the data

In [236]:
import pandas as pd
fake=pd.read_csv('E:/nbn/fake-news.csv',encoding='utf-8')
real=pd.read_csv('E:/nbn/real-news.csv',encoding='utf-8')
real['label']=1
fake['label']=0
real=real[:5000]
fake=fake[:5000]
df=pd.concat([real,fake])
df.head()

text  label
0  سحبت شركة غوغل في خطوة مفاجئة خدمة يوتيوب الشه...      1
1  عاد لاعب باريس سان جيرمان  البرازيلي نيمار دا ...      1
2  أخبارنا المغربية ـ متابعة   في أول رد للبرلمان...      1
3  شيرين تتهرب من المؤتمر الصحفي لمهرجان تطوان و ...      1
4  منظمو أولمبياد طوكيو 2020 يطالبون بالتبرع باله...      1

## preprocessing

# shuffel the data

In [237]:
from sklearn.utils import shuffle
df=shuffle(df)
df.head()

text  label
4595  أعلنت جمعية مغرب الثقافات  اليوم الإثنين  أن ا...      1
1877  أخبارنا المغربية   و م ع  أدت صاحبة السمو المل...      1
1991  كشفت شركة سامسونغ  يوم الأحد  هاتفيها المرتقبي...      1
1231  الابتكارات في مجال سرقة السيارات لا تتوقف ودائ...      1
2952  جماهير الأفريقي تتضامن مع القدس بـ تيفو  ضخم  ...      1

# reset indexes

In [238]:
df=df.sample(frac=1).reset_index(drop=True)
df.head()

text  label
0  الشفاعة فضل من الله تعالى يكرم به بعض عباده يو...      1
1  صور لمحاولة سرقة امرأة مسنة عن طريق دراجة ناري...      0
2  فتاة جامعية تخي ب أمل والدتها  وتفشل بتحصيل عر...      0
3  طرحت  هواوي  خلال العام الجاري  تشكيلة من هوات...      1
4  أفاد مصدر من الوقاية المدنية أن حريقا شب ليلة ...      1

In [239]:

def remove_stopwords():
    file=open('E:/nbn/stopwords.txt','r',encoding='utf-8')
    ss=file.read()

    stop_words=ss.split()
    result_data.delete("1.0",END)
    text=rawdata.get("1.0",END)
    results=[]
    for word in text.split():
        if word not in stop_words:

            results.append(word)
    result_data.insert("1.0"," - ".join(results))


In [240]:
def choose_text():
    import random
    n=random.randint(0,len(df))
    rawdata.delete('1.0',END)
    rawdata.insert("1.0",df['text'][n])

In [241]:
def splitting():
    result_data.delete("1.0",END)
    text=rawdata.get("1.0",END)
    results=[]
    for word in text.split():
        results.append(word)
    result_data.insert("1.0"," - ".join(results))
def stemming():
    result_data.delete("1.0",END)
    text=rawdata.get("1.0",END)
    results=[]
    for word in text.split():
        arabic_stemmer.light_stem(word)
        results.append(arabic_stemmer.get_stem())
    result_data.insert("1.0"," - ".join(results))
def get_root():
    
    result_data.delete("1.0",END)
    text=rawdata.get("1.0",END)
    results=[]
    for word in text.split():
        arabic_stemmer.light_stem(word)
        results.append(arabic_stemmer.get_root())
    result_data.insert("1.0"," - ".join(results))


In [242]:
def segmentation():
    result_data.delete("1.0",END)
    text=rawdata.get("1.0",END)
    results=[]
    for word in text.split('.'):
        results.append(word)
    result_data.insert("1.0"," - ".join(results))

In [243]:
top=Tk()
top.title('Fake News')
top.geometry("500x600") 
label1=Label(top,text='Enter your Text')
rawdata=Text(top,height=15,width=60,)
label2=Label(top,text='Result')
result_data=Text(top,height=15,width=60,)
stem_button=Button(top,text="Stem",command=stemming)
segmentation_button=Button(top,text="Segmentation",command=segmentation)
get_root_button=Button(top,text="Get Root",command=get_root)
split_button=Button(top,text="Split Text",command=splitting)
stopwords_button=Button(top,text="Remove StopWords",command=remove_stopwords)

random_button=Button(top,text="Random text from data",command=choose_text)
label1.grid(row=0,columnspan=6)
rawdata.grid(row=1,columnspan=6)
label2.grid(row=2,columnspan=6)
result_data.grid(row=3,columnspan=6)
split_button.grid(row=4,column=0)
segmentation_button.grid(row=4,column=1)
stopwords_button.grid(row=4,column=2)
stem_button.grid(row=4,column=3)
get_root_button.grid(row=4,column=4)
random_button.grid(row=4,column=5)

top.mainloop()

In [244]:
def segmentation(text):
    results=[]
    for word in text.split('.'):
        results.append(word)
    return " ".join(results)

In [245]:
def splitting(text):
    results=[]
    for word in text.split():
        results.append(word)
    return " ".join(results)

In [246]:
def remove_stopwords(text):
    file=open('E:/nbn/stopwords.txt','r',encoding='utf-8')
    ss=file.read()

    stop_words=ss.split()
    results=[]
    for word in text.split():
        if word not in stop_words:

            results.append(word)
    return " ".join(results)


In [247]:
def remove_punctuation(text):
    import string
    punc=list(string.punctuation)
    t=[]
    for word in text.split(): 
        if word not in punc:
            t.append(word)
            
    return " ".join(t)

In [248]:

def stemming(text):

    results=[]
    for word in text.split():
        results.append(arabic_stemmer.light_stem(word))
    return " ".join(results)


In [249]:

def get_root(text):
    results=[]
    for word in text.split():
        arabic_stemmer.light_stem(word)
        results.append(arabic_stemmer.get_root())
    return " ".join(results)


# applay the preprocessing

In [250]:
df['text']=df['text'].apply(remove_stopwords)
df['text']=df['text'].apply(remove_punctuation)
df['text']=df['text'].apply(get_root)


# Naive Bayes with Tf_Idf

In [251]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
#feature extraction
tfidf_vec=TfidfVectorizer()
tfidf_features=tfidf_vec.fit_transform(df['text'])
#split data into train and test
x_train,x_test,y_train,y_test=train_test_split(tfidf_features,df['label'],test_size=0.2)

In [252]:
print(x_train.shape)
print(x_test.shape)

(8000, 16693)
(2000, 16693)


In [253]:
# classifier
from sklearn.naive_bayes import MultinomialNB
tfidf_model=MultinomialNB()
tfidf_model.fit(x_train,y_train)

MultinomialNB()

# accurcy

In [254]:
import numpy as np
tfidf_predected=tfidf_model.predict(x_test)
print(np.mean(tfidf_predected==y_test))

0.9195


# confusion matrix

In [255]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,tfidf_predected))

[[862 127]
 [ 34 977]]


# Naive Bayes with Binary Encoding

In [256]:
from sklearn.feature_extraction.text import CountVectorizer
binary_vec=CountVectorizer(binary=True)
binary_features=binary_vec.fit_transform(df['text'])
x_train,x_test,y_train,y_test=train_test_split(binary_features,df['label'],test_size=0.2)

In [257]:
# classefier
binary_model=MultinomialNB()
binary_model.fit(x_train,y_train)

MultinomialNB()

# accurcy

In [258]:
binary_predicted=binary_model.predict(x_test)
print(np.mean(binary_predicted==y_test))

0.9045


# Confusion Matrix

In [259]:
print(confusion_matrix(binary_predicted,y_test))

[[841  48]
 [143 968]]


# Naive Bayes with Tf_Idf

In [260]:
count_vec=CountVectorizer()
count_features=count_vec.fit_transform(df['text'])
x_train,x_test,y_train,y_test=train_test_split(count_features,df['label'],test_size=0.2)
count_model=MultinomialNB()
count_model.fit(x_train,y_train)

MultinomialNB()

# accurcy

In [261]:
count_predicted=count_model.predict(x_test)
print(np.mean(count_predicted==y_test))

0.9075


# Confusion Matrix

In [262]:
print(confusion_matrix(count_predicted,y_test))

[[856  39]
 [146 959]]
